# Целевая версия Python
target-version = "py312"

# Длина строки
line-length = 88

# Пути, которые считаем "проектными" (first-party) для импорта/isort
src = ["app"]

# Ruff уже исключает по умолчанию `.git`, `.venv`, `__pycache__` и т.п.
# Здесь добавляем специфичные для Django-проекта директории.
extend-exclude = [
    "**/migrations/**",
    "staticfiles/**",
]

[lint]
# Включаем правила
select = [
    "E",   # pycodestyle errors
    "W",   # pycodestyle warnings
    "F",   # pyflakes
    "I",   # isort
    "B",   # flake8-bugbear
    "C4",  # flake8-comprehensions
    "UP",  # pyupgrade
    "DJ",  # flake8-django
]

# Игнорируем некоторые правила
ignore = [
    "E501",  # line too long (handled by formatter)
    "B008",  # do not perform function calls in argument defaults
]
